--------------------------------------------------------
--  File created - Tuesday-January-13-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPROVALS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."APPROVALS" 
   (	"APPROVAL_ID" NUMBER(10,0), 
	"LOAN_REQUEST_ID" NUMBER(10,0), 
	"APPROVER_ID" NUMBER(10,0), 
	"APPROVAL_LEVEL" NUMBER(1,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"NOTES" CLOB, 
	"APPROVED_AT" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTES") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DRIVERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DRIVERS" 
   (	"DRIVER_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"LICENSE_NUMBER" VARCHAR2(50 BYTE), 
	"LICENSE_EXPIRY" DATE, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'AVAILABLE', 
	"EXPERIENCE_YEARS" NUMBER(2,0), 
	"RATING" NUMBER(3,2) DEFAULT 5.00, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOAN_REQUESTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOAN_REQUESTS" 
   (	"LOAN_REQUEST_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"DESTINATION" VARCHAR2(255 BYTE), 
	"PURPOSE" CLOB, 
	"START_DATETIME" TIMESTAMP (6), 
	"END_DATETIME" TIMESTAMP (6), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'SUBMITTED', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"SERVICE_LETTER_BASIS" VARCHAR2(200 BYTE) DEFAULT ' ', 
	"HOTEL_ACCOMMODATION" VARCHAR2(200 BYTE), 
	"VEHICLE_ID" NUMBER(10,0), 
	"DRIVER_ID" NUMBER(10,0), 
	"GUEST_LIST" VARCHAR2(500 BYTE) DEFAULT 'N/A', 
	"SERVICE_LETTER_FILE_PATH" VARCHAR2(500 BYTE), 
	"NOTES" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PURPOSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SYSTEM"."LOAN_REQUESTS"."HOTEL_ACCOMMODATION" IS 'Hotel accommodation details (optional)';
   COMMENT ON COLUMN "SYSTEM"."LOAN_REQUESTS"."VEHICLE_ID" IS 'Requested vehicle ID (required)';
   COMMENT ON COLUMN "SYSTEM"."LOAN_REQUESTS"."DRIVER_ID" IS 'Requested driver ID (required)';
   COMMENT ON COLUMN "SYSTEM"."LOAN_REQUESTS"."GUEST_LIST" IS 'List of guests being served (required)';
   COMMENT ON COLUMN "SYSTEM"."LOAN_REQUESTS"."NOTES" IS 'Notes from the requester (pemohon)';
--------------------------------------------------------
--  DDL for Table SCHEDULES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SCHEDULES" 
   (	"SCHEDULE_ID" NUMBER(10,0), 
	"LOAN_REQUEST_ID" NUMBER(10,0), 
	"DRIVER_ID" NUMBER(10,0), 
	"VEHICLE_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"ASSIGNED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"NOTES" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTES") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"USER_ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"DIVISION" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UNIT_KERJA" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."USERS"."UNIT_KERJA" IS 'Unit kerja/bagian dari user';
--------------------------------------------------------
--  DDL for Table VEHICLES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VEHICLES" 
   (	"VEHICLE_ID" NUMBER(10,0), 
	"LICENSE_PLATE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"BRAND" VARCHAR2(50 BYTE), 
	"MODEL" VARCHAR2(50 BYTE), 
	"YEAR" NUMBER(4,0), 
	"CAPACITY" NUMBER(2,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'AVAILABLE', 
	"LAST_MAINTENANCE" DATE, 
	"NEXT_MAINTENANCE" DATE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_APPROVALS_LOAN_REQUEST
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_APPROVALS_LOAN_REQUEST" ON "SYSTEM"."APPROVALS" ("LOAN_REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_APPROVALS_APPROVER
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_APPROVALS_APPROVER" ON "SYSTEM"."APPROVALS" ("APPROVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_APPROVALS_LEVEL_STATUS
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_APPROVALS_LEVEL_STATUS" ON "SYSTEM"."APPROVALS" ("APPROVAL_LEVEL", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008428
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008428" ON "SYSTEM"."APPROVALS" ("APPROVAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_DRIVERS_STATUS
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_DRIVERS_STATUS" ON "SYSTEM"."DRIVERS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_DRIVERS_USER_ID
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_DRIVERS_USER_ID" ON "SYSTEM"."DRIVERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008410
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008410" ON "SYSTEM"."DRIVERS" ("DRIVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008411
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008411" ON "SYSTEM"."DRIVERS" ("LICENSE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_LOAN_REQUESTS_USER_ID
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_LOAN_REQUESTS_USER_ID" ON "SYSTEM"."LOAN_REQUESTS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_LOAN_REQUESTS_STATUS
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_LOAN_REQUESTS_STATUS" ON "SYSTEM"."LOAN_REQUESTS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_LOAN_REQUESTS_DATES
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_LOAN_REQUESTS_DATES" ON "SYSTEM"."LOAN_REQUESTS" ("START_DATETIME", "END_DATETIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008420
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008420" ON "SYSTEM"."LOAN_REQUESTS" ("LOAN_REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_SCHEDULES_DRIVER
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_SCHEDULES_DRIVER" ON "SYSTEM"."SCHEDULES" ("DRIVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_SCHEDULES_VEHICLE
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_SCHEDULES_VEHICLE" ON "SYSTEM"."SCHEDULES" ("VEHICLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_SCHEDULES_STATUS
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_SCHEDULES_STATUS" ON "SYSTEM"."SCHEDULES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008433
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008433" ON "SYSTEM"."SCHEDULES" ("SCHEDULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008394
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008394" ON "SYSTEM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008395
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008395" ON "SYSTEM"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008396
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008396" ON "SYSTEM"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_USERS_ROLE
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_USERS_ROLE" ON "SYSTEM"."USERS" ("ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_USERS_DIVISION
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_USERS_DIVISION" ON "SYSTEM"."USERS" ("DIVISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_VEHICLES_TYPE
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_VEHICLES_TYPE" ON "SYSTEM"."VEHICLES" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008404
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008404" ON "SYSTEM"."VEHICLES" ("VEHICLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008405
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008405" ON "SYSTEM"."VEHICLES" ("LICENSE_PLATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_VEHICLES_STATUS
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."IDX_VEHICLES_STATUS" ON "SYSTEM"."VEHICLES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table APPROVALS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."APPROVALS" MODIFY ("LOAN_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPROVALS" MODIFY ("APPROVER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPROVALS" MODIFY ("APPROVAL_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPROVALS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPROVALS" ADD CHECK (approval_level IN (1, 2)) ENABLE;
  ALTER TABLE "SYSTEM"."APPROVALS" ADD CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')) ENABLE;
  ALTER TABLE "SYSTEM"."APPROVALS" ADD PRIMARY KEY ("APPROVAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DRIVERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DRIVERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DRIVERS" MODIFY ("LICENSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DRIVERS" MODIFY ("LICENSE_EXPIRY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DRIVERS" ADD CHECK (status IN ('AVAILABLE', 'ON_DUTY', 'OFF_DUTY', 'LEAVE')) ENABLE;
  ALTER TABLE "SYSTEM"."DRIVERS" ADD PRIMARY KEY ("DRIVER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DRIVERS" ADD UNIQUE ("LICENSE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAN_REQUESTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("DESTINATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("END_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" ADD CHECK (status IN ('SUBMITTED', 'APPROVED_L1', 'REJECTED_L1', 'APPROVED_L2', 'REJECTED_L2', 'SCHEDULED', 'WAITING_RESOURCE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')) ENABLE;
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" ADD PRIMARY KEY ("LOAN_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("SERVICE_LETTER_BASIS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" MODIFY ("GUEST_LIST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SCHEDULES" MODIFY ("LOAN_REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SCHEDULES" ADD CHECK (status IN ('PENDING', 'CONFIRMED', 'WAITING_DRIVER', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EMERGENCY')) ENABLE;
  ALTER TABLE "SYSTEM"."SCHEDULES" ADD PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" ADD CHECK (role IN ('PEMOHON', 'PIC_APPROVAL_L1', 'PIC_APPROVAL_L2', 'DRIVER', 'ADMIN')) ENABLE;
  ALTER TABLE "SYSTEM"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICLES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("LICENSE_PLATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("BRAND" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VEHICLES" ADD CHECK (status IN ('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'RETIRED')) ENABLE;
  ALTER TABLE "SYSTEM"."VEHICLES" ADD PRIMARY KEY ("VEHICLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."VEHICLES" ADD UNIQUE ("LICENSE_PLATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVALS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."APPROVALS" ADD FOREIGN KEY ("LOAN_REQUEST_ID")
	  REFERENCES "SYSTEM"."LOAN_REQUESTS" ("LOAN_REQUEST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."APPROVALS" ADD FOREIGN KEY ("APPROVER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DRIVERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DRIVERS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOAN_REQUESTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" ADD CONSTRAINT "FK_LOAN_REQUESTS_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "SYSTEM"."DRIVERS" ("DRIVER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."LOAN_REQUESTS" ADD CONSTRAINT "FK_LOAN_REQUESTS_VEHICLE" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "SYSTEM"."VEHICLES" ("VEHICLE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SCHEDULES" ADD FOREIGN KEY ("LOAN_REQUEST_ID")
	  REFERENCES "SYSTEM"."LOAN_REQUESTS" ("LOAN_REQUEST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."SCHEDULES" ADD FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "SYSTEM"."DRIVERS" ("DRIVER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."SCHEDULES" ADD FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "SYSTEM"."VEHICLES" ("VEHICLE_ID") ENABLE;
