-- Simple UPDATE SCHEDULES constraint statement

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SYSTEM.SCHEDULES DROP CONSTRAINT SYS_C008432';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

ALTER TABLE SYSTEM.SCHEDULES ADD CHECK (status IN ('PENDING', 'CONFIRMED', 'WAITING_DRIVER', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EMERGENCY')) ENABLE;

COMMIT;
